### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by mtshare** [iMokhles/TweakApp#3]
Hi, the app won't open
! It keeps jump in my dock.

iMac (27'', late 2009)
2,8 GHz Intel Core i7
12 GB DDR3 a 1067 MHz
OSX 10.11.4

![schermata 2016-04-08 alle 19 40 16](https://cloud.githubusercontent.com/assets/387165/14392466/bf206154-fdc1-11e5-90c9-3829aa24bb03.png)

**Comment by zzHAMZAzz** [comment]
Same for me. (Although it's over a year old, but I'm needing to try it xD)

MBA 2015
macOS 10.13

**Comment by iMokhles** [comment]
hey TweakApp is out dated . now you should use IMSign ( which could work ) i didn't check it also since the last release

**Comment by NiccoJS** [comment]
IMSign also stuck on startup
